name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update 3D profile card
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: abd84
          MAX_REPOS: 10

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update 3D contribution card"
          add: "profile-3d-contrib/*"
          default_author: github_actions
